#!/usr/bin/env python3
"""i18n_bundle: check site/i18n/*.json and write site/static/i18n.js from them (MIP-0054 §5.8).

    scripts/i18n_bundle.py               # validate, then (re)write site/static/i18n.js
    scripts/i18n_bundle.py --check       # validate, and exit 1 if the committed i18n.js is stale
    scripts/i18n_bundle.py --self-test

Gates: (1) every locale has exactly pt-BR.json's keys and no empty value; (2) every message parses
in the ICU subset ui.js implements ({arg}, plural, select) and names the same arguments as pt-BR's;
(3) every key has a note in context.json. The x-pseudo locale is generated, never translated.
"""

import argparse
import contextlib
import io
import json
import math
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
I18N_DIR = ROOT / "site" / "i18n"
OUT = ROOT / "site" / "static" / "i18n.js"
SOURCE = "pt-BR"
PSEUDO = "x-pseudo"
CONTEXT = "context.json"
HEADER = "// generated by scripts/i18n_bundle.py from site/i18n/*.json, do not edit\n"
PLURAL_KEYS = {"zero", "one", "two", "few", "many", "other"}
ACCENTS = str.maketrans("aeiouycnAEIOUYCN", "áéîõûýçñÁÉÎÕÛÝÇÑ")
WORD = re.compile(r"\s*([^\s,{}]+)\s*")


class ParseError(ValueError):
    pass


def parse(s):
    """A message as a list of str | {"hash"} | {"name", "type"?, "cases"?}; ParseError if not."""
    pos = 0

    def skip_ws():
        nonlocal pos
        while pos < len(s) and s[pos].isspace():
            pos += 1

    def word():
        nonlocal pos
        m = WORD.match(s, pos)
        if not m:
            raise ParseError(f"expected a name at {pos} in {s!r}")
        pos = m.end()
        return m.group(1)

    def expect(c):
        nonlocal pos
        if pos >= len(s) or s[pos] != c:
            raise ParseError(f"expected {c!r} at {pos} in {s!r}")
        pos += 1

    def message(in_plural):
        nonlocal pos
        out, text = [], ""
        while pos < len(s) and s[pos] != "}":
            c = s[pos]
            if c == "{" or (c == "#" and in_plural):
                if text:
                    out.append(text)
                    text = ""
                pos += 1
                out.append(argument(in_plural) if c == "{" else {"hash": True})
            else:
                text += c
                pos += 1
        if text:
            out.append(text)
        return out

    def argument(in_plural):
        nonlocal pos
        node = {"name": word()}
        if pos < len(s) and s[pos] == ",":
            pos += 1
            kind = word()
            if kind not in ("plural", "select"):
                raise ParseError(f"unsupported argument type {kind!r} in {s!r}")
            expect(",")
            node["type"], node["cases"] = kind, {}
            skip_ws()
            while pos < len(s) and s[pos] != "}":
                key = word()
                if kind == "plural" and key not in PLURAL_KEYS and not key.startswith("="):
                    raise ParseError(f"unknown plural category {key!r} in {s!r}")
                expect("{")
                node["cases"][key] = message(in_plural or kind == "plural")
                expect("}")
                skip_ws()
            if "other" not in node["cases"]:
                raise ParseError(f"{kind} without an 'other' case in {s!r}")
        expect("}")
        return node

    nodes = message(False)
    if pos != len(s):
        raise ParseError(f"unbalanced '}}' at {pos} in {s!r}")
    return nodes


def arg_names(nodes):
    names = set()
    for n in nodes:
        if isinstance(n, dict) and "name" in n:
            names.add(n["name"])
            for sub in n.get("cases", {}).values():
                names |= arg_names(sub)
    return names


def serialize(nodes, text_fn=lambda t: t):
    out = []
    for n in nodes:
        if isinstance(n, str):
            out.append(text_fn(n))
        elif "hash" in n:
            out.append("#")
        elif "type" not in n:
            out.append("{" + n["name"] + "}")
        else:
            cases = " ".join(k + " {" + serialize(v, text_fn) + "}" for k, v in n["cases"].items())
            out.append("{" + n["name"] + ", " + n["type"] + ", " + cases + "}")
    return "".join(out)


def pseudo(message):
    text = []
    accented = serialize(parse(message), lambda t: text.append(t) or t.translate(ACCENTS))
    return "⟦" + accented + " " + "·" * math.ceil(len("".join(text)) * 0.3) + "⟧"


def load(i18n_dir):
    locales, context, errors = {}, {}, []
    for f in sorted(i18n_dir.glob("*.json")):
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            errors.append(f"{f.name}: not JSON ({e})")
            continue
        if f.name == CONTEXT:
            context = data
        else:
            locales[f.stem] = data
    return locales, context, errors


def validate(locales, context):
    errors = []
    if SOURCE not in locales:
        return [f"no {SOURCE}.json, the source locale"]
    src = locales[SOURCE]
    src_args = {}
    for key, msg in src.items():
        try:
            src_args[key] = arg_names(parse(msg))
        except ParseError as e:
            errors.append(f"{SOURCE}.{key}: {e}")
    for lang, cat in sorted(locales.items()):
        for key in sorted(set(src) - set(cat)):
            errors.append(f"{lang}: missing key {key}")
        for key in sorted(set(cat) - set(src)):
            errors.append(f"{lang}: key {key} is not in {SOURCE}.json")
        for key, msg in sorted(cat.items()):
            if not isinstance(msg, str) or not msg.strip():
                errors.append(f"{lang}.{key}: empty value")
                continue
            if lang == SOURCE:
                continue
            try:
                names = arg_names(parse(msg))
            except ParseError as e:
                errors.append(f"{lang}.{key}: {e}")
                continue
            if key in src_args and names != src_args[key]:
                errors.append(
                    f"{lang}.{key}: arguments {sorted(names)} differ from {SOURCE}'s {sorted(src_args[key])}"
                )
    for key in sorted(set(src) - set(context)):
        errors.append(f"{CONTEXT}: no note for {key}")
    for key, note in sorted(context.items()):
        if key in src and not (isinstance(note, str) and note.strip()):
            errors.append(f"{CONTEXT}: empty note for {key}")
    return errors


def bundle(locales):
    data = dict(locales)
    data[PSEUDO] = {k: pseudo(v) for k, v in locales[SOURCE].items()}
    body = json.dumps(data, ensure_ascii=False, indent=1, sort_keys=True)
    return HEADER + "window.MAROLA_I18N = " + body + ";\n"


def run(i18n_dir, out, check):
    locales, context, errors = load(i18n_dir)
    errors += validate(locales, context)
    if errors:
        for e in errors:
            print("i18n_bundle: " + e, file=sys.stderr)
        return 1
    text = bundle(locales)
    if check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != text:
            print(f"i18n_bundle: {out} is stale, run scripts/i18n_bundle.py", file=sys.stderr)
            return 1
        print(f"i18n_bundle: ok ({len(locales)} locales, {len(locales[SOURCE])} keys)")
        return 0
    out.write_text(text, encoding="utf-8")
    print(f"i18n_bundle: wrote {out}")
    return 0


def self_test():
    fails = 0

    def ok(cond, label):
        nonlocal fails
        print(("  ok   " if cond else "  FAIL ") + label)
        fails += 0 if cond else 1

    good = {
        "pt-BR": {"a": "olá {name}", "n": "{n, plural, one {# praia} other {# praias}}"},
        "en": {"a": "hi {name}", "n": "{n, plural, one {# beach} other {# beaches}}"},
    }
    notes = {"a": "greeting", "n": "beach count"}

    def scenario(label, cats, ctx, expect_ok, stale=False):
        with tempfile.TemporaryDirectory() as tmp:
            d = Path(tmp)
            for lang, cat in cats.items():
                (d / f"{lang}.json").write_text(json.dumps(cat), encoding="utf-8")
            (d / CONTEXT).write_text(json.dumps(ctx), encoding="utf-8")
            out = d / "i18n.js"
            with (
                contextlib.redirect_stdout(io.StringIO()),
                contextlib.redirect_stderr(io.StringIO()),
            ):
                run(d, out, check=False)
                if stale:
                    out.write_text(HEADER + "window.MAROLA_I18N = {};\n", encoding="utf-8")
                rc = run(d, out, check=True)
            ok((rc == 0) == expect_ok, label)

    def with_(lang, key, value):
        cats = json.loads(json.dumps(good))
        if value is None:
            del cats[lang][key]
        else:
            cats[lang][key] = value
        return cats

    scenario("a valid catalog set passes --check after a write", good, notes, True)
    scenario("a missing key fails", with_("en", "a", None), notes, False)
    scenario("an extra key fails", with_("en", "zz", "x"), notes, False)
    scenario("an empty value fails", with_("en", "a", "  "), notes, False)
    scenario("an argument missing in one locale fails", with_("en", "a", "hi there"), notes, False)
    scenario("a renamed argument fails", with_("en", "a", "hi {nome}"), notes, False)
    scenario("an unparsable message fails", with_("en", "n", "{n, plural, one {# x}"), notes, False)
    scenario(
        "a plural with no other case fails", with_("en", "n", "{n, plural, one {#}}"), notes, False
    )
    scenario("a key with no context note fails", good, {"a": "greeting"}, False)
    scenario("a stale bundle fails", good, notes, False, stale=True)

    nodes = parse("às {h}{past, select, yes { (já passou)} other {}}")
    ok(arg_names(nodes) == {"h", "past"}, "arguments inside select cases are collected")
    ok(serialize(parse(good["pt-BR"]["n"])) == good["pt-BR"]["n"], "serialize round-trips a plural")
    p = pseudo("olá {name}, {n, plural, one {# praia} other {# praias}}")
    ok(p.startswith("⟦") and p.endswith("⟧"), "pseudo wraps the message in ⟦ ⟧")
    ok(
        "{name}" in p and "{n, plural, one {# práîá}" in p,
        "pseudo accents text, leaves argument names, keywords and # alone",
    )
    ok(
        arg_names(parse(p[1:-1])) == {"name", "n"},
        "pseudo output still parses with the same arguments",
    )

    if fails:
        print(f"i18n_bundle self-test: {fails} failure(s)")
        return 1
    print("i18n_bundle self-test: ok")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()
    if args.self_test:
        sys.exit(self_test())
    sys.exit(run(I18N_DIR, OUT, args.check))


if __name__ == "__main__":
    main()
