#!/usr/bin/env python3
"""news_build: write news.html's posts from site/content/news/*.md (MIP-0044 §5.3, #7).

    scripts/news_build.py               # validate, then (re)write the posts in site/static/news.html
    scripts/news_build.py --check       # validate, and exit 1 if the committed news.html is stale
    scripts/news_build.py --self-test

A post is one file per language, `YYYY-MM-DD-<slug>.<lang>.md`, in pt-BR and en; the format is in
site/content/news/README.md. Only the Markdown that format names is rendered; anything else is an
error, so a post never reaches the page half-rendered.
"""

import argparse
import contextlib
import html
import io
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
POSTS = ROOT / "site" / "content" / "news"
PAGE = ROOT / "site" / "static" / "news.html"
LANGS = ("pt-BR", "en")
BEGIN = (
    "<!-- news:begin, generated by scripts/news_build.py from site/content/news/, do not edit -->"
)
END = "<!-- news:end -->"
NAME = re.compile(r"^(\d{4})-(\d{2})-(\d{2})-([a-z0-9-]+)\.(pt-BR|en)\.md$")
# A common silent-reading rate for non-fiction; the minutes are rounded up so a short post says 1.
WORDS_PER_MINUTE = 200
READ = {"pt-BR": "{} min de leitura", "en": "{} min read"}
MONTHS = {
    "pt-BR": "janeiro fevereiro março abril maio junho julho agosto setembro outubro novembro dezembro",
    "en": "January February March April May June July August September October November December",
}


class PostError(ValueError):
    pass


def inline(text):
    out = html.escape(text, quote=False)
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", out)
    out = re.sub(
        r"\[([^\]]+)\]\(([^)\s]+)\)",
        lambda m: f'<a href="{html.escape(html.unescape(m.group(2)))}">{m.group(1)}</a>',
        out,
    )
    if re.search(r"[*_`\[\]]", re.sub(r"<[^>]+>", "", out)):
        raise PostError(f"unsupported Markdown in: {text}")
    return out


def words(blocks):
    """The words a reader reads: no link targets, no Markdown markup."""
    text = re.sub(r"\]\([^)]*\)", " ", " ".join(blocks))
    return [w for w in re.sub(r"[#*`\[\]]|^- ", " ", text).split() if re.search(r"\w", w)]


def reading_minutes(blocks):
    return max(1, -(-len(words(blocks)) // WORDS_PER_MINUTE))


def render(path):
    """One post file as (date, slug, lang, <article> HTML); PostError if it breaks the format."""
    m = NAME.match(path.name)
    if not m:
        raise PostError(f"{path.name}: not YYYY-MM-DD-<slug>.<pt-BR|en>.md")
    y, mo, d, slug, lang = m.groups()
    blocks = [b.strip() for b in path.read_text(encoding="utf-8").split("\n\n") if b.strip()]
    if len(blocks) < 3 or not blocks[0].startswith("# ") or "\n" in blocks[0]:
        raise PostError(f"{path.name}: needs a '# title', a date line and a lede")
    if blocks[1] != f"{y}-{mo}-{d}":
        raise PostError(f"{path.name}: the date line must be {y}-{mo}-{d}, the file's date")
    month = MONTHS[lang].split()[int(mo) - 1]
    shown = f"{int(d)} de {month} de {y}" if lang == "pt-BR" else f"{month} {int(d)}, {y}"
    out = [
        f'    <article class="about-body" lang="{lang}">',
        f"      <h2>{inline(blocks[0][2:])}</h2>",
        f'      <p class="post-date"><time datetime="{y}-{mo}-{d}">{shown}</time>'
        f" · {READ[lang].format(reading_minutes([blocks[0], *blocks[2:]]))}</p>",
    ]
    if blocks[2].startswith(("#", "- ")):
        raise PostError(f"{path.name}: the paragraph after the date is the lede")
    out.append(f'      <p class="lede">{inline(" ".join(blocks[2].split()))}</p>')
    for b in blocks[3:]:
        if b.startswith("## ") and "\n" not in b:
            out.append(f"      <h2>{inline(b[3:])}</h2>")
        elif b.startswith("### ") and "\n" not in b:
            out.append(f"      <h3>{inline(b[4:])}</h3>")
        elif b.startswith("#"):
            raise PostError(f"{path.name}: only ## and ### headings inside a post: {b[:40]}")
        elif b.startswith("- "):
            items = re.split(r"\n- ", b[2:])
            out.append("      <ul>")
            out += [f"        <li>{inline(' '.join(i.split()))}</li>" for i in items]
            out.append("      </ul>")
        else:
            out.append(f"      <p>{inline(' '.join(b.split()))}</p>")
    out.append("    </article>")
    return f"{y}-{mo}-{d}", slug, lang, "\n".join(out)


def build(posts_dir):
    posts = [render(p) for p in sorted(posts_dir.glob("*.md")) if p.name != "README.md"]
    if not posts:
        raise PostError(f"{posts_dir}: no posts")
    keys = {lang: {(d, s) for d, s, lg, _ in posts if lg == lang} for lang in LANGS}
    for missing in keys["pt-BR"] ^ keys["en"]:
        raise PostError(f"{missing[0]}-{missing[1]}: needs both a .pt-BR.md and an .en.md")
    index = (
        (posts_dir / "README.md").read_text(encoding="utf-8")
        if (posts_dir / "README.md").exists()
        else ""
    )
    for d, s in sorted(keys["pt-BR"]):
        if f"{d}-{s}" not in index:
            raise PostError(f"{d}-{s}: not listed in {posts_dir.name}/README.md's index")
    # Newest first, every pt-BR post before every en one: the page shows one language at a time.
    ordered = sorted(
        posts, key=lambda p: (LANGS.index(p[2]), [-int(x) for x in p[0].split("-")], p[1])
    )
    return "\n\n".join(p[3] for p in ordered)


def run(posts_dir, page, check):
    try:
        articles = build(posts_dir)
    except PostError as e:
        print(f"news_build: {e}", file=sys.stderr)
        return 1
    text = page.read_text(encoding="utf-8")
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        print(f"news_build: {page.name} needs one '{BEGIN}' and one '{END}'", file=sys.stderr)
        return 1
    head, rest = text.split(BEGIN)
    _, tail = rest.split(END)
    new = f"{head}{BEGIN}\n{articles}\n    {END}{tail}"
    if new == text:
        print(f"news_build: ok ({articles.count('<article')} articles)")
        return 0
    if check:
        print(f"news_build: {page.name} is stale, run scripts/news_build.py", file=sys.stderr)
        return 1
    page.write_text(new, encoding="utf-8")
    print(f"news_build: wrote {page.name}")
    return 0


def self_test():
    fails = 0

    def ok(cond, label):
        nonlocal fails
        print(f"  {'ok  ' if cond else 'FAIL'} {label}")
        fails += 0 if cond else 1

    pt = "# olá\n\n2026-10-07\n\num lede.\n\n## seção\n\n- um [link](https://x.org/?a=1&b=2)\n- **dois**\n"
    en = "# hello\n\n2026-10-07\n\nA lede.\n\n### sub\n\nText with `code`.\n"
    page = f"<main>\n    {BEGIN}\n    {END}\n</main>\n"

    def scenario(label, files, expect_ok, index="2026-10-07-a"):
        with tempfile.TemporaryDirectory() as tmp:
            d = Path(tmp)
            (d / "README.md").write_text(index)
            for name, body in files.items():
                (d / name).write_text(body)
            out = d / "news.html"
            out.write_text(page)
            with (
                contextlib.redirect_stdout(io.StringIO()),
                contextlib.redirect_stderr(io.StringIO()),
            ):
                run(d, out, check=False)
                rc = run(d, out, check=True)
            ok((rc == 0) == expect_ok, label)
            return out.read_text()

    good = {"2026-10-07-a.pt-BR.md": pt, "2026-10-07-a.en.md": en}
    got = scenario("a post in both languages passes --check after a write", good, True)
    ok(
        '<time datetime="2026-10-07">7 de outubro de 2026</time> · 1 min de leitura</p>' in got,
        "pt-BR date",
    )
    ok("October 7, 2026</time> · 1 min read</p>" in got, "en date and reading time")
    ok(reading_minutes(["# t", "word " * 200]) == 2, "201 words round up to 2 minutes")
    ok(
        len(words(["[two words](https://a.org/x/y/z)", "- **one** ·"])) == 3,
        "link targets and markup are not counted",
    )
    ok('<p class="lede">um lede.</p>' in got, "the paragraph after the date is the lede")
    ok('<a href="https://x.org/?a=1&amp;b=2">link</a>' in got, "a link's & is escaped once")
    ok("<li><b>dois</b></li>" in got and "<code>code</code>" in got, "bold and code render")
    ok(got.index('lang="pt-BR"') < got.index('lang="en"'), "pt-BR articles come before en")
    scenario("a post with no en file fails", {"2026-10-07-a.pt-BR.md": pt}, False)
    scenario(
        "a date line that is not the file's date fails",
        {**good, "2026-10-07-a.en.md": en.replace("2026-10-07", "2026-10-08")},
        False,
    )
    scenario("a badly named file fails", {**good, "post.en.md": en}, False)
    scenario(
        "an unsupported heading fails", {**good, "2026-10-07-a.en.md": en + "\n#### deep\n"}, False
    )
    scenario("leftover Markdown fails", {**good, "2026-10-07-a.en.md": en + "\n_italic_\n"}, False)
    scenario(
        "raw HTML is escaped, not passed through",
        {**good, "2026-10-07-a.en.md": en + "\n<script>x</script>\n"},
        True,
    )
    scenario("a post missing from the README index fails", good, False, index="")
    newer = {
        **good,
        "2026-10-09-b.pt-BR.md": pt.replace("2026-10-07", "2026-10-09"),
        "2026-10-09-b.en.md": en.replace("2026-10-07", "2026-10-09"),
    }
    got = scenario("two posts pass", newer, True, index="2026-10-07-a 2026-10-09-b")
    ok(got.index('datetime="2026-10-09"') < got.index('datetime="2026-10-07"'), "newest first")

    if fails:
        print(f"news_build self-test: {fails} failure(s)")
        return 1
    print("news_build self-test: ok")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()
    if args.self_test:
        sys.exit(self_test())
    sys.exit(run(POSTS, PAGE, args.check))


if __name__ == "__main__":
    main()
