#!/usr/bin/env python3
"""posts_build: write each section's posts from site/content/<section>/*.md (MIP-0044 §5.3, #7, #102).

    scripts/posts_build.py               # validate, then (re)write the posts of every section's page
    scripts/posts_build.py --check       # validate, and exit 1 if a committed page is stale
    scripts/posts_build.py --self-test

A section is a directory of posts and the page they are written into (SECTIONS). A post is one file
per language, `YYYY-MM-DD-<slug>.<lang>.md`, in pt-BR and en; the format is in
site/content/news/README.md. Only the Markdown that format names is rendered; anything else is an
error, so a post never reaches the page half-rendered. A page that also carries an index block gets
the list of its posts and the tags they use, declared in the section's tags.json.
"""

import argparse
import contextlib
import html
import io
import json
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "site" / "content"
STATIC = ROOT / "site" / "static"
SECTIONS = {"news": "news.html", "blog": "blog.html"}
LANGS = ("pt-BR", "en")
NAME = re.compile(r"^(\d{4})-(\d{2})-(\d{2})-([a-z0-9-]+)\.(pt-BR|en)\.md$")
TAGS = re.compile(r"^tags: ([a-z0-9-]+(?:, [a-z0-9-]+)*)$")
# A common silent-reading rate for non-fiction; the minutes are rounded up so a short post says 1.
WORDS_PER_MINUTE = 200
READ = {"pt-BR": "{} min de leitura", "en": "{} min read"}
INDEX_HEADS = {"pt-BR": ("posts", "tags"), "en": ("posts", "tags")}
POSTS_COUNT = {"pt-BR": ("1 post", "{} posts"), "en": ("1 post", "{} posts")}
RELEASE = re.compile(r"^::: release (v\d+\.\d+\.\d+) (\d{4})-(\d{2})-(\d{2})$")
RELEASES = "https://github.com/marola-dev/marola/releases/tag/"
MONTHS = {
    "pt-BR": "janeiro fevereiro março abril maio junho julho agosto setembro outubro novembro dezembro",
    "en": "January February March April May June July August September October November December",
}


class PostError(ValueError):
    pass


def markers(section):
    gen = f"generated by scripts/posts_build.py from site/content/{section}/, do not edit"
    return {
        "posts": (f"<!-- {section}:begin, {gen} -->", f"<!-- {section}:end -->"),
        "index": (f"<!-- {section}-index:begin, {gen} -->", f"<!-- {section}-index:end -->"),
    }


def anchor(name, lang):
    return f"{name}-{lang.lower()}"


def inline(text):
    out = html.escape(text, quote=False)
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", out)
    out = re.sub(
        r"\[([^\]]+)\]\(([^)\s]+)\)",
        lambda m: f'<a href="{html.escape(html.unescape(m.group(2)))}">{m.group(1)}</a>',
        out,
    )
    if re.search(r"[*_`\[\]]", re.sub(r"<[^>]+>", "", out)):
        raise PostError(f"unsupported Markdown in: {text}")
    return out


def long_date(lang, y, mo, d):
    month = MONTHS[lang].split()[int(mo) - 1]
    return f"{int(d)} de {month} de {y}" if lang == "pt-BR" else f"{month} {int(d)}, {y}"


def release_card(lang, block, name):
    """`::: release vX.Y.Z YYYY-MM-DD`, then `- ` highlights, then one line of links."""
    head, *lines = block.split("\n")
    m = RELEASE.match(head)
    if not m or not lines:
        raise PostError(f"{name}: '::: release vX.Y.Z YYYY-MM-DD' then its lines: {head}")
    tag, y, mo, d = m.groups()
    items, links = [], []
    for line in lines:
        (items if line.startswith("- ") else links).append(line.removeprefix("- "))
    if not items or len(links) != 1:
        raise PostError(f"{name}: a release card needs '- ' highlights and one line of links")
    out = [
        '      <aside class="release">',
        '        <p class="release-head">'
        f'<a class="release-tag" href="{RELEASES}{tag}">marola {tag}</a>'
        f' <time datetime="{y}-{mo}-{d}">{long_date(lang, y, mo, d)}</time></p>',
        "        <ul>",
        *[f"          <li>{inline(i)}</li>" for i in items],
        "        </ul>",
        f'        <p class="release-links">{inline(links[0])}</p>',
        "      </aside>",
    ]
    return out


def words(blocks):
    """The words a reader reads: no link targets, no Markdown markup."""
    text = re.sub(r"\]\([^)]*\)|^::: .*$", " ", " ".join(blocks), flags=re.M)
    return [w for w in re.sub(r"[#*`\[\]]|^- ", " ", text).split() if re.search(r"\w", w)]


def reading_minutes(blocks):
    return max(1, -(-len(words(blocks)) // WORDS_PER_MINUTE))


def tag_links(tags, lang, registry):
    links = " ".join(
        f'<a class="tag" href="#{anchor("tag-" + t, lang)}">{html.escape(registry[t][lang]["name"])}</a>'
        for t in tags
    )
    return f'<p class="post-tags">{links}</p>'


def render(path, registry):
    """One post file as a dict with its date, slug, lang, tags, title, minutes and <article> HTML."""
    m = NAME.match(path.name)
    if not m:
        raise PostError(f"{path.name}: not YYYY-MM-DD-<slug>.<pt-BR|en>.md")
    y, mo, d, slug, lang = m.groups()
    blocks = [b.strip() for b in path.read_text(encoding="utf-8").split("\n\n") if b.strip()]
    if len(blocks) < 3 or not blocks[0].startswith("# ") or "\n" in blocks[0]:
        raise PostError(f"{path.name}: needs a '# title', a date line and a lede")
    if blocks[1] != f"{y}-{mo}-{d}":
        raise PostError(f"{path.name}: the date line must be {y}-{mo}-{d}, the file's date")
    tags = []
    if blocks[2].startswith("tags:"):
        t = TAGS.match(blocks[2])
        if not t:
            raise PostError(f"{path.name}: 'tags: a, b', lowercase slugs: {blocks[2]}")
        tags = t.group(1).split(", ")
        for tag in tags:
            if tag not in registry:
                raise PostError(f"{path.name}: tag '{tag}' is not declared in tags.json")
        del blocks[2]
    if len(blocks) < 3:
        raise PostError(f"{path.name}: needs a lede")
    minutes = reading_minutes([blocks[0], *blocks[2:]])
    shown = long_date(lang, y, mo, d)
    attrs = f' data-tags="{" ".join(tags)}"' if tags else ""
    out = [
        f'    <article class="about-body" lang="{lang}" id="{anchor(slug, lang)}"{attrs}>',
        f"      <h2>{inline(blocks[0][2:])}</h2>",
        f'      <p class="post-date"><time datetime="{y}-{mo}-{d}">{shown}</time>'
        f" · {READ[lang].format(minutes)}</p>",
    ]
    if tags:
        out.append(f"      {tag_links(tags, lang, registry)}")
    if blocks[2].startswith(("#", "- ")):
        raise PostError(f"{path.name}: the paragraph after the date is the lede")
    out.append(f'      <p class="lede">{inline(" ".join(blocks[2].split()))}</p>')
    for b in blocks[3:]:
        if b.startswith("## ") and "\n" not in b:
            out.append(f"      <h2>{inline(b[3:])}</h2>")
        elif b.startswith("### ") and "\n" not in b:
            out.append(f"      <h3>{inline(b[4:])}</h3>")
        elif b.startswith("::: "):
            out += release_card(lang, b, path.name)
        elif b.startswith("#"):
            raise PostError(f"{path.name}: only ## and ### headings inside a post: {b[:40]}")
        elif b.startswith("- "):
            items = re.split(r"\n- ", b[2:])
            out.append("      <ul>")
            out += [f"        <li>{inline(' '.join(i.split()))}</li>" for i in items]
            out.append("      </ul>")
        else:
            out.append(f"      <p>{inline(' '.join(b.split()))}</p>")
    out.append("    </article>")
    return {
        "date": f"{y}-{mo}-{d}",
        "slug": slug,
        "lang": lang,
        "tags": tags,
        "title": inline(blocks[0][2:]),
        "minutes": minutes,
        "html": "\n".join(out),
    }


def load_tags(posts_dir):
    """tags.json: {"<slug>": {"pt-BR": {"name", "about"}, "en": {"name", "about"}}}, optional."""
    path = posts_dir / "tags.json"
    if not path.exists():
        return {}
    registry = json.loads(path.read_text(encoding="utf-8"))
    for tag, langs in registry.items():
        if not re.fullmatch(r"[a-z0-9-]+", tag):
            raise PostError(f"tags.json: '{tag}' is not a lowercase slug")
        for lang in LANGS:
            entry = langs.get(lang, {})
            if not entry.get("name") or not entry.get("about"):
                raise PostError(f"tags.json: '{tag}' needs a name and an about in {lang}")
    return registry


def index(posts, registry):
    """Per language: the posts newest first, then each tag in use with what it means."""
    out = []
    for lang in LANGS:
        mine = [p for p in posts if p["lang"] == lang]
        posts_head, tags_head = INDEX_HEADS[lang]
        out += [
            f'    <section class="about-body post-index" lang="{lang}">',
            f"      <h3>{posts_head}</h3>",
            '      <ol class="post-list">',
        ]
        for p in mine:
            y, mo, d = p["date"].split("-")
            tags = f" {tag_links(p['tags'], lang, registry)}" if p["tags"] else ""
            out.append(
                f'        <li><a href="#{anchor(p["slug"], lang)}">{p["title"]}</a>'
                f' <p class="post-date"><time datetime="{p["date"]}">{long_date(lang, y, mo, d)}</time>'
                f" · {READ[lang].format(p['minutes'])}</p>{tags}</li>"
            )
        out.append("      </ol>")
        used = sorted({t for p in mine for t in p["tags"]})
        if used:
            out += [f"      <h3>{tags_head}</h3>", '      <dl class="tag-list">']
            for t in used:
                n = sum(t in p["tags"] for p in mine)
                count = POSTS_COUNT[lang][0] if n == 1 else POSTS_COUNT[lang][1].format(n)
                entry = registry[t][lang]
                out += [
                    f'        <dt id="{anchor("tag-" + t, lang)}">{html.escape(entry["name"])}</dt>',
                    f"        <dd>{inline(entry['about'])} ({count})</dd>",
                ]
            out.append("      </dl>")
        out.append("    </section>")
    return "\n".join(out)


def build(posts_dir):
    """The posts' HTML and the index's, newest first, every pt-BR one before every en one."""
    registry = load_tags(posts_dir)
    posts = [render(p, registry) for p in sorted(posts_dir.glob("*.md")) if p.name != "README.md"]
    if not posts:
        raise PostError(f"{posts_dir}: no posts")
    keys = {lang: {(p["date"], p["slug"]) for p in posts if p["lang"] == lang} for lang in LANGS}
    for missing in keys["pt-BR"] ^ keys["en"]:
        raise PostError(f"{missing[0]}-{missing[1]}: needs both a .pt-BR.md and an .en.md")
    tags = {(p["date"], p["slug"]): p["tags"] for p in posts if p["lang"] == "pt-BR"}
    for p in posts:
        if p["tags"] != tags[(p["date"], p["slug"])]:
            raise PostError(f"{p['date']}-{p['slug']}: pt-BR and en carry different tags")
    readme = posts_dir / "README.md"
    listed = readme.read_text(encoding="utf-8") if readme.exists() else ""
    for d, s in sorted(keys["pt-BR"]):
        if f"{d}-{s}" not in listed:
            raise PostError(f"{d}-{s}: not listed in {posts_dir.name}/README.md's index")
    # The page shows one language at a time, so each language's posts sit together.
    ordered = sorted(
        posts,
        key=lambda p: (LANGS.index(p["lang"]), [-int(x) for x in p["date"].split("-")], p["slug"]),
    )
    return "\n\n".join(p["html"] for p in ordered), index(ordered, registry)


def replace_block(text, begin, end, body):
    head, rest = text.split(begin)
    _, tail = rest.split(end)
    return f"{head}{begin}\n{body}\n    {end}{tail}"


def run(section, posts_dir, page, check):
    try:
        articles, listing = build(posts_dir)
    except PostError as e:
        print(f"posts_build: {section}: {e}", file=sys.stderr)
        return 1
    text = page.read_text(encoding="utf-8")
    mk = markers(section)
    begin, end = mk["posts"]
    if text.count(begin) != 1 or text.count(end) != 1:
        print(f"posts_build: {page.name} needs one '{begin}' and one '{end}'", file=sys.stderr)
        return 1
    new = replace_block(text, begin, end, articles)
    ibegin, iend = mk["index"]
    if ibegin in new:
        if new.count(ibegin) != 1 or new.count(iend) != 1:
            print(
                f"posts_build: {page.name} needs one '{ibegin}' and one '{iend}'", file=sys.stderr
            )
            return 1
        new = replace_block(new, ibegin, iend, listing)
    if new == text:
        print(f"posts_build: {section} ok ({articles.count('<article')} articles)")
        return 0
    if check:
        print(f"posts_build: {page.name} is stale, run scripts/posts_build.py", file=sys.stderr)
        return 1
    page.write_text(new, encoding="utf-8")
    print(f"posts_build: wrote {page.name}")
    return 0


def self_test():
    fails = 0

    def ok(cond, label):
        nonlocal fails
        print(f"  {'ok  ' if cond else 'FAIL'} {label}")
        fails += 0 if cond else 1

    pt = "# olá\n\n2026-10-07\n\num lede.\n\n## seção\n\n- um [link](https://x.org/?a=1&b=2)\n- **dois**\n"
    en = "# hello\n\n2026-10-07\n\nA lede.\n\n### sub\n\nText with `code`.\n"
    mk = markers("s")
    page = f"<main>\n    {mk['posts'][0]}\n    {mk['posts'][1]}\n</main>\n"
    indexed = f"<main>\n    {mk['index'][0]}\n    {mk['index'][1]}\n{page}"
    adr = {
        "adr": {
            "pt-BR": {"name": "ADR", "about": "uma decisão"},
            "en": {"name": "ADR", "about": "a decision"},
        }
    }

    def scenario(label, files, expect_ok, index="2026-10-07-a", tags=None, html_page=page):
        with tempfile.TemporaryDirectory() as tmp:
            d = Path(tmp)
            (d / "README.md").write_text(index)
            if tags is not None:
                (d / "tags.json").write_text(json.dumps(tags))
            for name, body in files.items():
                (d / name).write_text(body)
            out = d / "page.html"
            out.write_text(html_page)
            with (
                contextlib.redirect_stdout(io.StringIO()),
                contextlib.redirect_stderr(io.StringIO()),
            ):
                run("s", d, out, check=False)
                rc = run("s", d, out, check=True)
            ok((rc == 0) == expect_ok, label)
            return out.read_text()

    good = {"2026-10-07-a.pt-BR.md": pt, "2026-10-07-a.en.md": en}
    got = scenario("a post in both languages passes --check after a write", good, True)
    ok(
        '<time datetime="2026-10-07">7 de outubro de 2026</time> · 1 min de leitura</p>' in got,
        "pt-BR date",
    )
    ok("October 7, 2026</time> · 1 min read</p>" in got, "en date and reading time")
    ok(reading_minutes(["# t", "word " * 200]) == 2, "201 words round up to 2 minutes")
    ok(
        len(words(["[two words](https://a.org/x/y/z)", "- **one** ·"])) == 3,
        "link targets and markup are not counted",
    )
    ok('<p class="lede">um lede.</p>' in got, "the paragraph after the date is the lede")
    ok('<a href="https://x.org/?a=1&amp;b=2">link</a>' in got, "a link's & is escaped once")
    ok("<li><b>dois</b></li>" in got and "<code>code</code>" in got, "bold and code render")
    ok(got.index('lang="pt-BR"') < got.index('lang="en"'), "pt-BR articles come before en")
    ok('id="a-pt-br"' in got and 'id="a-en"' in got, "each article has an anchor per language")
    card = "::: release v0.2.1 2026-10-08\n- a [change](https://x.org/1)\n[notes](https://x.org/n) · DOI"
    got = scenario(
        "a release card renders", {**good, "2026-10-07-a.en.md": en + "\n" + card + "\n"}, True
    )
    ok(
        'href="https://github.com/marola-dev/marola/releases/tag/v0.2.1">marola v0.2.1</a>' in got
        and "October 8, 2026" in got
        and '<p class="release-links"><a href="https://x.org/n">notes</a> · DOI</p>' in got,
        "the card has the tag, its date, highlights and links",
    )
    scenario(
        "a release card with no links line fails",
        {**good, "2026-10-07-a.en.md": en + "\n::: release v0.2.1 2026-10-08\n- one\n"},
        False,
    )
    scenario("a post with no en file fails", {"2026-10-07-a.pt-BR.md": pt}, False)
    scenario(
        "a date line that is not the file's date fails",
        {**good, "2026-10-07-a.en.md": en.replace("2026-10-07", "2026-10-08")},
        False,
    )
    scenario("a badly named file fails", {**good, "post.en.md": en}, False)
    scenario(
        "an unsupported heading fails", {**good, "2026-10-07-a.en.md": en + "\n#### deep\n"}, False
    )
    scenario("leftover Markdown fails", {**good, "2026-10-07-a.en.md": en + "\n_italic_\n"}, False)
    scenario(
        "raw HTML is escaped, not passed through",
        {**good, "2026-10-07-a.en.md": en + "\n<script>x</script>\n"},
        True,
    )
    scenario("a post missing from the README index fails", good, False, index="")
    newer = {
        **good,
        "2026-10-09-b.pt-BR.md": pt.replace("2026-10-07", "2026-10-09"),
        "2026-10-09-b.en.md": en.replace("2026-10-07", "2026-10-09"),
    }
    got = scenario("two posts pass", newer, True, index="2026-10-07-a 2026-10-09-b")
    ok(got.index('datetime="2026-10-09"') < got.index('datetime="2026-10-07"'), "newest first")

    def tagged(text):
        return text.replace("2026-10-07\n\n", "2026-10-07\n\ntags: adr\n\n", 1)

    both = {"2026-10-07-a.pt-BR.md": tagged(pt), "2026-10-07-a.en.md": tagged(en)}
    got = scenario("a tagged post with a declared tag passes", both, True, tags=adr)
    ok(
        'data-tags="adr"' in got and '<a class="tag" href="#tag-adr-en">ADR</a>' in got,
        "a tagged post carries its tags and links each to the index",
    )
    ok('<p class="lede">A lede.</p>' in got, "the tags line is not the lede")
    scenario("an undeclared tag fails", both, False)
    scenario(
        "a tag missing a language fails",
        both,
        False,
        tags={"adr": {"pt-BR": {"name": "ADR", "about": "x"}}},
    )
    scenario(
        "pt-BR and en with different tags fail",
        {**both, "2026-10-07-a.en.md": en},
        False,
        tags=adr,
    )
    scenario(
        "a malformed tags line fails",
        {**both, "2026-10-07-a.en.md": en.replace("2026-10-07\n\n", "2026-10-07\n\ntags: ADR\n\n")},
        False,
        tags=adr,
    )
    got = scenario("a page with an index block gets it", both, True, tags=adr, html_page=indexed)
    ok(
        '<section class="about-body post-index" lang="en">' in got
        and '<li><a href="#a-en">hello</a>' in got
        and '<dt id="tag-adr-pt-br">ADR</dt>' in got
        and "<dd>a decision (1 post)</dd>" in got,
        "the index lists the posts and each tag with what it means",
    )
    ok("post-index" not in scenario("no index block, no index", good, True), "index is opt-in")

    if fails:
        print(f"posts_build self-test: {fails} failure(s)")
        return 1
    print("posts_build self-test: ok")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()
    if args.self_test:
        sys.exit(self_test())
    rc = 0
    for section, page in SECTIONS.items():
        rc |= run(section, CONTENT / section, STATIC / page, args.check)
    sys.exit(rc)


if __name__ == "__main__":
    main()
